### ISSUE TITLE
Can't use wordlist with aspell: 'The language "en" is not known'

### ISSUE THREAD

**Issue by langston-barrett** [facelessuser/pyspelling#114]
I have this configuration:
```yaml
spellchecker: aspell
matrix:
- name: Org
  aspell:
    lang: en
  dictionary:
    wordlists:
    - meta/words.txt
    output: meta/build/words.dic
  sources:
  - "*.org"
```
`pyspelling` errors:
```
Problem compiling dictionary. Check the binary path and options.
Traceback (most recent call last):
  File "/some/path/venv/bin/pyspelling", line 8, in <module>
    sys.exit(main())
  File "/some/path/venv/lib/python3.7/site-packages/pyspelling/__main__.py", line 34, in main
    debug=args.debug
  File "/some/path/venv/lib/python3.7/site-packages/pyspelling/__main__.py", line 59, in run
    debug=debug
  File "/some/path/venv/lib/python3.7/site-packages/pyspelling/__init__.py", line 666, in spellcheck
    for result in spellchecker.run_task(task, source_patterns=sources):
  File "/some/path/venv/lib/python3.7/site-packages/pyspelling/__init__.py", line 301, in run_task
    personal_dict = self.setup_dictionary(task)
  File "/some/path/venv/lib/python3.7/site-packages/pyspelling/__init__.py", line 344, in setup_dictionary
    output
  File "/some/path/venv/lib/python3.7/site-packages/pyspelling/__init__.py", line 387, in compile_dictionary
    input_text=b'\n'.join(sorted(words)) + b'\n'
  File "/some/path/venv/lib/python3.7/site-packages/pyspelling/util/__init__.py", line 105, in call
    return get_process_output(process, encoding)
  File "/some/path/venv/lib/python3.7/site-packages/pyspelling/util/__init__.py", line 89, in get_process_output
    raise RuntimeError("Runtime Error: %s" % (output[0].rstrip().decode(encoding, errors='replace')))
RuntimeError: Runtime Error: Error: The language "en" is not known. This is probably because: the file "/nix/store/7174mliyxm98v9f54jjl3afqbwx6v399-aspell-0.60.8/lib/aspell/en.dat" can not be opened for reading.
```
That file does not exist:
```
ls /nix/store/7174mliyxm98v9f54jjl3afqbwx6v399-aspell-0.60.8/lib/aspell                                                              <<<
ccpp.amf             cp1254.cset        html.amf          iso-8859-1.cmap  iso-8859-8.cmap       nroff.amf          tex-filter.la
comment.amf          cp1255.cmap        html-filter.info  iso-8859-1.cset  iso-8859-8.cset       nroff-filter.info  tex-filter.so
context-filter.info  cp1255.cset        iso-8859-10.cmap  iso-8859-2.cmap  iso-8859-9.cmap       nroff-filter.la    texinfo.amf
context-filter.la    cp1256.cmap        iso-8859-10.cset  iso-8859-2.cset  iso-8859-9.cset       nroff-filter.so    texinfo-filter.info
context-filter.so    cp1256.cset        iso-8859-11.cmap  iso-8859-3.cmap  ispell                perl.amf           texinfo-filter.la
cp1250.cmap          cp1257.cmap        iso-8859-11.cset  iso-8859-3.cset  koi8-r.cmap           sgml.amf           texinfo-filter.so
cp1250.cset          cp1257.cset        iso-8859-13.cmap  iso-8859-4.cmap  koi8-r.cset           sgml-filter.info   u-deva.cmap
cp1251.cmap          cp1258.cmap        iso-8859-13.cset  iso-8859-4.cset  koi8-u.cmap           sgml-filter.la     u-deva.cset
cp1251.cset          cp1258.cset        iso-8859-14.cmap  iso-8859-5.cmap  koi8-u.cset           sgml-filter.so     url.amf
cp1252.cmap          dvorak.kbd         iso-8859-14.cset  iso-8859-5.cset  markdown.amf          spell
cp1252.cset          email.amf          iso-8859-15.cmap  iso-8859-6.cmap  markdown-filter.info  split.kbd
cp1253.cmap          email-filter.info  iso-8859-15.cset  iso-8859-6.cset  markdown-filter.la    standard.kbd
cp1253.cset          email-filter.la    iso-8859-16.cmap  iso-8859-7.cmap  markdown-filter.so    tex.amf
cp1254.cmap          email-filter.so    iso-8859-16.cset  iso-8859-7.cset  none.amf              tex-filter.info
```

**Comment by facelessuser** [comment]
What did you install? Unfortunately, I am not certain what you have installed. When I use in my CI, I install both `aspell` and `aspell-en`: https://github.com/facelessuser/pyspelling/blob/master/.github/workflows/pullrequest.yml#L69.

**Comment by facelessuser** [comment]
Moving to support as most likely a user setup issue.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by facelessuser** [comment]
Linked wrong issue.

**Comment by facelessuser** [comment]
@gir-bot add S: more-info-needed

I'll give this until the end of the week to get more info. If none is provided, I'll assume the issue was resolved.

**Comment by facelessuser** [comment]
This issue is stale, closing.
